# @package hydra.job_logging
# python logging configuration for tasks
version: 1
formatters:
  simple:
    format: "[%(asctime)s][%(name)s][%(levelname)s] - %(message)s"
  short:
    format: "%(message)s"
handlers:
  console:
    class: src.utils.log_utils.CustomRichHandler
    formatter: short
  file:
    class: logging.FileHandler
    formatter: simple
    # relative to the job log directory
    filename: ${hydra.job.name}.log
root:
  level: INFO
  handlers: [console, file]

disable_existing_loggers: false
