# @package model.reconstructor

_target_: src.models.reconstructor.chain.ChainReconstructor
_recursive_: false

lm:
  _target_: src.models.components.rnn_lm.RNNModel

kl_scheduler:
  _target_: src.models.reconstructor.schedulers.get_frange_cycle_linear_sheduler
  start: 0.
  stop: 1.
  n_epoch: 1000 # period of total scheduler
  n_cycle: 2
  ratio: 0.5
