# @package model.reconstructor

_target_: src.models.reconstructor.simple2.Simple2Reconstructor
_recursive_: false

embedding:
  _target_: torch.nn.Embedding
  embedding_dim: 64
encoder:
  _target_: src.models.components.encoder.StandardLSTM
  hidden_size: 64
  bidirectional: true
  dropout: 0.2
  num_layers: 1
