_target_: pytorch_lightning.Trainer

gpus: -1
auto_select_gpus: True

min_epochs: 1
max_epochs: 5
precision: 32
weights_summary: full
accumulate_grad_batches: null
gradient_clip_val: 5
strategy: "deepspeed_stage_3"
auto_scale_batch_size: "binsearch"

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

# ckpt path
resume_from_checkpoint: null
