# @package model.decoder

defaults:
  - none

rule_soft_constraint:
  _target_: src.models.constraint.folded.FSimpleHierarchy
rule_soft_constraint_solver:
  _target_: src.models.posterior_regularization.linear.UngroundedPRLineSearchSolver
  b: 0
  field: slr
