# @package model.decoder

defaults:
  - none

rule_soft_constraint:
  _target_: src.models.constraint.fully_parameterized.FPPenaltyDepthAndNonIntersection
  upwards_score: 0.1
  stay_score: 0.9
  intersect_score: 0.1
  nt_temperature: 1.
  pt_temperature: 1.

rule_hard_constraint:
  _target_: src.models.constraint.fully_parameterized.FPSimpleHierarchy
