# @package model.decoder

defaults:
  - none

rule_soft_constraint:
  _target_: src.models.constraint.fully_parameterized.FPSynchronous
rule_soft_constraint_solver:
  _target_: src.models.posterior_regularization.linear.UngroundedPRLineSearchSolver
  b: 0
