# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: rich
  - override job_logging: rich

job:
  chdir: true
run:
  dir: logs/${name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: logs/${name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}
