_target_: src.utils.metric.MultiMetric
bleu-1:
  _target_: src.utils.metric.BLEUScore
  n_gram: 1
  has_subword: true
bleu-2:
  _target_: src.utils.metric.BLEUScore
  n_gram: 2
  has_subword: true
bleu-3:
  _target_: src.utils.metric.BLEUScore
  n_gram: 3
  has_subword: true
bleu-4:
  _target_: src.utils.metric.BLEUScore
  n_gram: 4
  has_subword: true
