_target_: src.utils.metric.MultiMetric
bleu-1:
  _target_: torchmetrics.BLEUScore
  n_gram: 1
bleu-2:
  _target_: torchmetrics.BLEUScore
  n_gram: 2
bleu-3:
  _target_: torchmetrics.BLEUScore
  n_gram: 3
bleu-4:
  _target_: torchmetrics.BLEUScore
  n_gram: 4
exact:
  _target_: src.utils.metric.WholeSentMatchAccuracy
