_target_: src.utils.metric.MultiMetric

denotion:
  _target_: src.utils.metric.GeoDenotionMetric

  executor:
    _target_: src.utils.executor.ProgramExecutorGeo
    geobase_pl: ${data_dir}/geo/geobase.pl
    geoquery_pl: ${data_dir}/geo/geoquery.pl
    eval_pl: ${data_dir}/geo/eval.pl

exact:
  _target_: src.utils.metric.WholeSentMatchAccuracy
