_target_: src.models.tgt_parser.neural_nodecomp.NeuralNoDecompTgtParser
_recursive_: false

# base
pt_states: 8
nt_states: 8
pt_span_range: [1, 1]
nt_span_range: [2, 1000]
use_copy: true
rule_hard_constraint: ~
rule_soft_constraint:
  ~
  # _target_: src.models.constraint.fully_parameterized.FPSimpleHierarchy
rule_soft_constraint_solver:
  ~
  # _target_: src.models.posterior_regularization.linear.UngroundedPRLineSearchSolver
  # b: 0
generation_max_length: 40
generation_num_samples: 10
generation_ppl_batch_size: 1

# NeuralQCFGTgtParser
dim: 512
num_layers: 3
