_target_: src.models.tgt_parser.neural_qcfg_rdp.NeuralQCFGRDPTgtParser
num_layers: 3
dim: 512
nt_states: 8 # src_nt_states in origin impl
pt_states: 8 # src_pt_states in origin impl
rule_constraint_type: 1
use_copy: true
num_samples: 8
check_ppl: true
rdp_topk: 10
rdp_sample_size: 14
