# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric: "val/f1_best"

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: "mysql://optuna:L-eabVd7-qqTaBZ4_i@127.0.0.1:28873/optuna"

    # name of the study to persist optimization results
    study_name: ner_fw_tree

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: maximize

    # total number of runs that will be executed
    n_trials: 1000

    # choose Optuna hyperparameter sampler
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: null
      n_startup_trials: 10 # number of random sampling runs before optimization starts

    # define range of hyperparameters
    search_space:
      model.crf.layernorm:
        type: categorical
        choices: [true, false]
      model.crf.iterations:
        type: categorical
        choices: [1, 2, 3, 4, 5]
      model.crf.params.scheme:
        type: categorical
        choices: ["standard", "linesearch", "learnable", "fixed"]
      model.crf.params.lambda_:
        type: float
        low: 0.5
        high: 1.0
      model.crf.params.x0_weight:
        type: float
        low: 0.0
        high: 0.5
