defaults:
  - encoder: empty
  - parser: pcfg
  - tree_encoder: treelstm
  - decoder: qcfg
  - test_metric: bleu1234_and_exact

_target_: src.models.general_seq2seq.GeneralSeq2SeqModule
_recursive_: false

param_initializer: "xavier_uniform"
track_param_norm: false

embedding:
  _target_: torch.nn.Embedding
  embedding_dim: 256

decoder:
  dim: 256
  nt_states: 10 # src_nt_states in origin impl
  pt_states: 1 # src_pt_states in origin impl
  rule_constraint_type: 1
  use_copy: false
  num_samples: 8
  check_ppl: true

optimizer:
  groups: ~
  args:
    _target_: torch.optim.Adam
    lr: 5.0e-4
    betas: [0.75, 0.999]
    weight_decay: 1.0e-5
    eps: 1.0e-8

scheduler: ~
