defaults:
  - encoder: yzhang_lstm
  - parser: pcfg
  - tree_encoder: treelstm
  - decoder: qcfg
  - test_metric: bleu1234

_target_: src.models.gseq2seq_src_span_v1.GSeq2seqSrcSpanV1
_recursive_: false

embedding:
  _target_: torch.nn.Embedding
  embedding_dim: 300

param_initializer: "xavier_uniform"
track_param_norm: false

optimizer:
  groups: ~
  args:
    _target_: torch.optim.Adam
    lr: 5.0e-4
    betas: [0.75, 0.999]
    weight_decay: 1.0e-5
    eps: 1.0e-8

scheduler: ~
