defaults:
  - encoder: yzhang_lstm
  - parser: pcfg
  - tree_encoder: treelstm
  - decoder: qcfg
  - test_metric: bleu1234

_target_: src.models.gseq2seq_pr.GSeq2SeqPosterioirRegularizationModule
_recursive_: false

param_initializer: "xavier_uniform"
track_param_norm: false

embedding:
  _target_: torch.nn.Embedding
  embedding_dim: 300

decoder:
  rule_constraint_type: 1
  rule_constraint_method: pr
  rule_constraint_method_args:
    b: 2
    lbound: 1e-3
    rbound: 1e2
    num_point: 6
    num_iter: 5

optimizer:
  groups: ~
  args:
    _target_: torch.optim.AdamW
    lr: 5.0e-4
    betas: [0.75, 0.999]
    weight_decay: 1.0e-5
    eps: 1.0e-8

scheduler:
  interval: step
  frequency: 1
  monitor: val/ppl
  args:
    _target_: src.utils.scheduler.get_exponential_lr_scheduler
    gamma: 0.75**(1/10000)
