defaults:
  - encoder: yzhang_lstm
  - parser: pcfg
  - tree_encoder: treelstm
  - decoder: nodecomp
  - test_metric: bleu1234

_target_: src.models.general_seq2seq_raml.GeneralSeq2SeqModule
_recursive_: false

param_initializer: "xavier_uniform"
track_param_norm: false

embedding:
  _target_: torch.nn.Embedding
  embedding_dim: 300

decoder:
  rule_soft_constraint:
    _target_: src.models.constraint.fully_parameterized.FPPenaltyDepth
    upwards_score: 0.2
    stay_score: 0.2
    down1_score: 1.
    down2_score: 0.85
    down3_score: 0.7
    down_score: 0.55
  rule_soft_constraint_solver:
    _target_: src.models.posterior_regularization.linear.UngroundedPRLineSearchSolver
    b: 0
optimizer:
  groups: ~
  args:
    _target_: torch.optim.AdamW
    lr: 5.0e-4
    betas: [0.75, 0.999]
    weight_decay: 1.0e-5
    eps: 1.0e-8

scheduler:
  ~
  # interval: step
  # frequency: 1
  # monitor: val/ppl
  # args:
  #   _target_: src.utils.scheduler.get_exponential_lr_scheduler
  #   gamma: 0.75**(1/10000)
