# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: ace05.yaml # choose the datamodule for evaluation
  - model: nested_ner_v2.yaml
  - callbacks: null
  - logger: null
  - trainer: default.yaml
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

hydra:
  job:
    chdir: true
    
original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/

print_config: True

ignore_warnings: True

seed: null

name: "default"

# passing checkpoint path is necessary
ckpt_path: ???
