_target_: src.datamodules.penman_datamodule.PenmanDataModule

train_file: ${data_dir}/AMR/tdata_xfm/debug.txt
dev_file: ${data_dir}/AMR/tdata_xfm/debug.txt
test_file: ${data_dir}/AMR/tdata_xfm/debug.txt
# train_file: ${data_dir}/AMR/tdata_xfm/dev.toy.txt
# dev_file: ${data_dir}/AMR/tdata_xfm/dev.toy.txt
# test_file: ${data_dir}/AMR/tdata_xfm/dev.toy.txt

copy_mode: "token"
max_src_len: 32

batch_size: 4
token_size: 100
eval_batch_size: 1
num_workers: ${in_debugger:0,4}
pin_memory: true

cache_dir: ${data_dir}/cache
enable_cache: false
