_target_: src.datamodules.arithmetic_datamodule.ArithmeticDataModule

train_file: ${data_dir}/arithmetic/raw/train_10k.tsv
dev_file: ${data_dir}/arithmetic/raw/val_5k.tsv
# test_file: ${data_dir}/arithmetic/raw/test_5k.tsv
test_file: ${data_dir}/arithmetic/raw/gen_5k.tsv

copy_mode: "none"
max_src_len: 10000

batch_size: 1
eval_batch_size: 1 # ${in_debugger:2,6}
num_workers: ${in_debugger:0,4}
pin_memory: false

cache_dir: ${data_dir}/cache
enable_cache: false
