_target_: src.datamodules.semantic_parsing_datamodule.SemanticParsingDataModule

train_file: ${data_dir}/geo/funql/train_len.json
dev_file: ${data_dir}/geo/funql/dev_len.json
test_file: ${data_dir}/geo/funql/test_len.json

copy_mode: "phrase"
lexicon_mode: "geo"
max_src_len: 16

batch_size: 4
token_size: 0
eval_batch_size: 1
num_workers: ${in_debugger:0,4}
pin_memory: true

cache_dir: ${data_dir}/cache
enable_cache: false
