_target_: src.datamodules.tsv_2dir_datamodule.TSV2DirDataModule

train_file: ${data_dir}/MT/train_en-fr.txt
dev_file: ${data_dir}/MT/dev_en-fr.txt
test_file: ${data_dir}/MT/test_en-fr.txt

copy_mode: "none"
max_src_len: 60
vocab_min_freq: 1

batch_size: 1
eval_batch_size: 1 # ${in_debugger:2,6}
num_workers: ${in_debugger:0,4}
pin_memory: false

cache_dir: ${data_dir}/cache
enable_cache: false
