_target_: src.datamodules.tsv_datamodule.TSVDataModule

train_file: ${data_dir}/StylePTB/ATP/train.tsv
dev_file: ${data_dir}/StylePTB/ATP/valid.tsv
test_file: ${data_dir}/StylePTB/ATP/test.tsv

copy_mode: "phrase"
max_src_len: 60

batch_size: ${in_debugger:2,4}
eval_batch_size: 4 # ${in_debugger:2,6}
num_workers: ${in_debugger:0,4}
pin_memory: false

cache_dir: ${data_dir}/cache
enable_cache: true
