_target_: src.datamodules.tsv_2dir_datamodule.TSV2DirDataModule

# train_file: ${data_dir}/StylePTB/ATP/debug_val.tsv
# dev_file: ${data_dir}/StylePTB/ATP/debug_val.tsv
# test_file: ${data_dir}/StylePTB/ATP/debug_val.tsv
train_file: ${data_dir}/StylePTB/ATP/train.tsv
dev_file: ${data_dir}/StylePTB/ATP/valid.tsv
test_file: ${data_dir}/StylePTB/ATP/test.tsv

copy_mode: none
max_src_len: 60

batch_size: 1 #${in_debugger:2,4}
eval_batch_size: 1 # ${in_debugger:2,6}
num_workers: ${in_debugger:0,4}
pin_memory: false

cache_dir: ${data_dir}/cache
enable_cache: false
